### ISSUE TITLE
Ajax Methods?

### ISSUE THREAD

**Issue by pyros2097** [philplckthun/sprint#10]
What about light weight wrapper around XMLHttpRequest for supporting ajax methods like jquery does?

**Comment by Stephn-R** [comment]
@philplckthun, how would you like to go about doing this?

**Comment by philplckthun** [comment]
No, I would not support this at all. This is in my opinion both useless and not in this project's scope.

Sprint wants to be a slim wrapper for manipulating the DOM - nothing more.

Also there's a much greater effort of implementing some sugar for AJAX with Github's fetch.

https://github.com/github/fetch

**Comment by kofalt** [comment]
:+1: Agreed, fetch ± polyfill is the future & in line with the spirit of sprint :)

**Comment by Stephn-R** [comment]
Awesome thanks for the swift reponses guys
